### Create a machine
POST https://api.machines.dev/v1/apps/test-bighouse-keeper/machines
Content-Type: application/json
Authorization: Bearer xxx

{
  "name": "keeper-1",
  "region": "iad",
  "config": {
    "image": "registry.fly.io/test-bighouse-keeper",
    "metadata": {
      "hey": "ho"
    },
    "services": [
      {
        "ports": [
          {
            "port": 2181
          }
        ],
        "protocol": "tcp",
        "internal_port": 2181
      }
    ]
  }
}